---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: demo-app1-user-full-access
  namespace: demo-app1
subjects:
- kind: User
  name: demo-app1-user
  namespace: demo-app1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: demo-app1-user-full-access
