
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: demo-app1-user-full-access
  namespace: demo-app1
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
